version: '3.9'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: online_exam_postgres
    environment:
      POSTGRES_DB: online_exam_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - exam_network
    restart: unless-stopped

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: online_exam_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - exam_network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # RabbitMQ 消息队列
  rabbitmq:
    image: 18df28yeoak27u.xuanyuan.run/rabbitmq:3.12-management-alpine
    container_name: online_exam_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - exam_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # 后端应用
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: online_exam_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=online_exam_system
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_VHOST=/
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - PORT=8080
      - GIN_MODE=release
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - exam_network
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs

  # 前端应用
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: online_exam_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - exam_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  exam_network:
    driver: bridge