version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: exam_postgres
    environment:
      POSTGRES_DB: online_exam_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - exam_network

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: exam_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - exam_network

  # 后端 API 服务
  backend:
    build: .
    container_name: exam_backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:password@postgres:5432/online_exam_system?sslmode=disable
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=online-exam-system-jwt-secret-key-2024
      - GIN_MODE=debug
      - AI_API_KEY=
      - AI_URL=https://api.openai.com/v1/chat/completions
    depends_on:
      - postgres
      - redis
    networks:
      - exam_network
    restart: unless-stopped

  # pgAdmin (可选，用于数据库管理)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: exam_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - exam_network
    profiles:
      - tools

volumes:
  postgres_data:
  redis_data:

networks:
  exam_network:
    driver: bridge