-- 插入更多题目数据，确保每个科目有足够的题目支持练习
-- 每个科目增加至少20个题目，总共100+个题目

-- 数学题目 (科目ID: 1) - 增加20个题目
INSERT INTO questions (subject_id, type, title, content, options, answer, explanation, difficulty, score, created_by, status, knowledge_point, usage_count, correct_rate, created_at, updated_at) VALUES
(1, 'single', '不等式求解', '不等式 2x + 3 > 7 的解集是？', '["A. x > 2", "B. x < 2", "C. x > 5", "D. x < 5"]', 'A', '2x + 3 > 7，移项得 2x > 4，两边同除以2得 x > 2。', 1, 3, 2, 'published', '不等式', 10, 0.85, NOW(), NOW()),
(1, 'single', '对数运算', 'log₂8 的值是？', '["A. 2", "B. 3", "C. 4", "D. 8"]', 'B', 'log₂8 = log₂2³ = 3，因为2³ = 8。', 2, 4, 2, 'published', '对数', 8, 0.78, NOW(), NOW()),
(1, 'single', '排列组合', '从5个人中选3个人排成一排，有多少种排法？', '["A. 15", "B. 60", "C. 120", "D. 125"]', 'B', '这是排列问题，A₅³ = 5!/(5-3)! = 5×4×3 = 60。', 3, 5, 2, 'published', '排列组合', 12, 0.72, NOW(), NOW()),
(1, 'single', '数列求和', '等差数列 2, 5, 8, 11, ... 的前10项和是？', '["A. 155", "B. 165", "C. 175", "D. 185"]', 'A', '首项a₁=2，公差d=3，前n项和公式：Sₙ = n(2a₁+(n-1)d)/2，S₁₀ = 10(4+27)/2 = 155。', 2, 4, 2, 'published', '数列', 15, 0.80, NOW(), NOW()),
(1, 'single', '圆的方程', '圆心在原点，半径为3的圆的方程是？', '["A. x² + y² = 3", "B. x² + y² = 9", "C. x² + y² = 6", "D. (x-3)² + (y-3)² = 9"]', 'B', '圆心在原点(0,0)，半径为r的圆的标准方程是 x² + y² = r²，所以方程为 x² + y² = 9。', 1, 3, 2, 'published', '圆的方程', 18, 0.88, NOW(), NOW()),
(1, 'multiple', '函数性质', '函数 f(x) = x² - 2x + 1 具有哪些性质？', '["A. 开口向上", "B. 对称轴为 x = 1", "C. 最小值为 0", "D. 与x轴有两个交点"]', 'A,B,C', '函数 f(x) = (x-1)²，开口向上，对称轴为 x = 1，最小值为 0，与x轴只有一个交点。', 2, 4, 2, 'published', '二次函数', 14, 0.75, NOW(), NOW()),
(1, 'multiple', '三角恒等式', '下列哪些是正确的三角恒等式？', '["A. sin²x + cos²x = 1", "B. tan x = sin x / cos x", "C. sin(x+y) = sin x + sin y", "D. cos 2x = cos²x - sin²x"]', 'A,B,D', 'A、B、D都是正确的三角恒等式，C是错误的，正确的应该是 sin(x+y) = sin x cos y + cos x sin y。', 2, 4, 2, 'published', '三角恒等式', 16, 0.73, NOW(), NOW()),
(1, 'judge', '函数奇偶性', '函数 f(x) = x³ + x 是奇函数。', '[]', 'true', 'f(-x) = (-x)³ + (-x) = -x³ - x = -(x³ + x) = -f(x)，满足奇函数定义。', 2, 3, 2, 'published', '函数奇偶性', 11, 0.82, NOW(), NOW()),
(1, 'judge', '极限概念', 'lim(x→0) sin x / x = 1。', '[]', 'true', '这是一个重要的极限公式，当 x 趋近于 0 时，sin x / x 的极限值为 1。', 3, 4, 2, 'published', '极限', 9, 0.76, NOW(), NOW()),
(1, 'essay', '积分计算', '计算定积分 ∫₀¹ x² dx。', '[]', '∫₀¹ x² dx = [x³/3]₀¹ = 1/3 - 0 = 1/3', '根据积分的基本定理，先求原函数 x³/3，然后计算上限减下限的值。', 3, 5, 2, 'published', '积分', 7, 0.68, NOW(), NOW()),
(1, 'essay', '解方程组', '解方程组：x + y = 5, 2x - y = 1', '[]', 'x = 2, y = 3', '用消元法：第一个方程加第二个方程得 3x = 6，所以 x = 2，代入得 y = 3。', 2, 4, 2, 'published', '方程组', 13, 0.81, NOW(), NOW()),
(1, 'single', '概率计算', '掷一枚硬币两次，至少出现一次正面的概率是？', '["A. 1/4", "B. 1/2", "C. 3/4", "D. 1"]', 'C', '总共4种情况：正正、正反、反正、反反，其中3种至少有一次正面，所以概率为 3/4。', 2, 4, 2, 'published', '概率', 20, 0.85, NOW(), NOW()),
(1, 'single', '向量运算', '向量 a = (3, 4)，向量 b = (1, 2)，则 a·b = ？', '["A. 7", "B. 11", "C. 5", "D. 10"]', 'B', '向量数量积 a·b = 3×1 + 4×2 = 3 + 8 = 11。', 2, 3, 2, 'published', '向量', 17, 0.79, NOW(), NOW()),
(1, 'single', '复数运算', '复数 (1+i)² 的值是？', '["A. 2i", "B. 1+2i", "C. 2", "D. 1+i"]', 'A', '(1+i)² = 1² + 2×1×i + i² = 1 + 2i + (-1) = 2i。', 3, 4, 2, 'published', '复数', 8, 0.71, NOW(), NOW()),
(1, 'single', '立体几何', '正方体的体对角线长度与棱长的比值是？', '["A. √2", "B. √3", "C. 2", "D. 3"]', 'B', '设正方体棱长为a，体对角线长度为√(a²+a²+a²) = a√3，比值为√3。', 3, 4, 2, 'published', '立体几何', 12, 0.74, NOW(), NOW()),
(1, 'multiple', '数学归纳法', '用数学归纳法证明时需要哪些步骤？', '["A. 验证n=1时命题成立", "B. 假设n=k时命题成立", "C. 证明n=k+1时命题也成立", "D. 得出结论"]', 'A,B,C,D', '数学归纳法的完整步骤包括：验证初始情况、归纳假设、归纳推理和得出结论。', 3, 5, 2, 'published', '数学归纳法', 6, 0.67, NOW(), NOW()),
(1, 'judge', '函数连续性', '函数 f(x) = |x| 在 x = 0 处连续。', '[]', 'true', '虽然 |x| 在 x = 0 处不可导，但它是连续的，因为 lim(x→0) |x| = 0 = f(0)。', 3, 4, 2, 'published', '函数连续性', 10, 0.78, NOW(), NOW()),
(1, 'essay', '最值问题', '求函数 f(x) = x² - 4x + 5 在区间 [0, 3] 上的最大值和最小值。', '[]', '最小值为1（在x=2处），最大值为5（在x=0处）', '对称轴为 x = 2，在区间内。f(0) = 5，f(2) = 1，f(3) = 2，比较得最值。', 2, 5, 2, 'published', '最值问题', 14, 0.72, NOW(), NOW()),
(1, 'essay', '参数方程', '将参数方程 x = 2cos t, y = 3sin t 化为普通方程。', '[]', 'x²/4 + y²/9 = 1', '由 x = 2cos t 得 cos t = x/2，由 y = 3sin t 得 sin t = y/3，利用 cos²t + sin²t = 1。', 3, 4, 2, 'published', '参数方程', 8, 0.69, NOW(), NOW()),
(1, 'single', '数学建模', '某商品原价100元，先涨价20%，再降价20%，现价是多少？', '["A. 96元", "B. 100元", "C. 104元", "D. 80元"]', 'A', '涨价后：100×1.2 = 120元，再降价：120×0.8 = 96元。', 1, 3, 2, 'published', '百分比计算', 25, 0.89, NOW(), NOW()),

-- 语文题目 (科目ID: 2) - 增加20个题目
(2, 'single', '成语理解', '"画蛇添足"这个成语的寓意是？', '["A. 做事要细心", "B. 多此一举", "C. 技艺高超", "D. 勤奋努力"]', 'B', '"画蛇添足"比喻做了多余的事，不但无益，反而有害，即多此一举。', 1, 3, 2, 'published', '成语', 22, 0.91, NOW(), NOW()),
(2, 'single', '文学常识', '《红楼梦》的作者是？', '["A. 吴承恩", "B. 施耐庵", "C. 曹雪芹", "D. 罗贯中"]', 'C', '《红楼梦》是清代作家曹雪芹创作的章回体长篇小说，是中国古典四大名著之一。', 1, 2, 2, 'published', '文学常识', 28, 0.94, NOW(), NOW()),
(2, 'single', '诗词格律', '七言律诗共有多少句？', '["A. 4句", "B. 6句", "C. 8句", "D. 10句"]', 'C', '七言律诗是律诗的一种，每句七个字，共八句，分为首联、颔联、颈联、尾联。', 2, 3, 2, 'published', '诗词格律', 15, 0.83, NOW(), NOW()),
(2, 'single', '现代文阅读', '下列哪个词语最能体现"春天"的特点？', '["A. 萧瑟", "B. 生机勃勃", "C. 凋零", "D. 寂静"]', 'B', '春天是万物复苏的季节，"生机勃勃"最能体现春天充满活力和希望的特点。', 1, 2, 2, 'published', '现代文阅读', 30, 0.95, NOW(), NOW()),
(2, 'single', '语言文字运用', '"他的话让我茅塞顿开"中"茅塞顿开"的意思是？', '["A. 突然明白", "B. 非常困惑", "C. 十分愤怒", "D. 极其高兴"]', 'A', '"茅塞顿开"比喻思路闭塞，现在忽然开窍，突然明白了某个道理。', 2, 3, 2, 'published', '成语理解', 18, 0.87, NOW(), NOW()),
(2, 'multiple', '文言文虚词', '下列哪些是文言文中的虚词？', '["A. 之", "B. 其", "C. 山", "D. 而"]', 'A,B,D', '"之"、"其"、"而"都是文言文中的虚词，"山"是实词（名词）。', 3, 4, 2, 'published', '文言文虚词', 12, 0.75, NOW(), NOW()),
(2, 'multiple', '写作手法', '下列哪些属于写作手法？', '["A. 对比", "B. 象征", "C. 名词", "D. 伏笔"]', 'A,B,D', '对比、象征、伏笔都是写作手法，"名词"是词性，不是写作手法。', 2, 4, 2, 'published', '写作手法', 16, 0.78, NOW(), NOW()),
(2, 'judge', '标点符号', '书名号只能用来标示书籍的名称。', '[]', 'false', '书名号不仅用于书籍，还可用于报刊、文章、影视作品、歌曲、绘画等作品的名称。', 2, 3, 2, 'published', '标点符号', 20, 0.85, NOW(), NOW()),
(2, 'judge', '语法知识', '"学习语文很重要"这句话的主语是"学习语文"。', '[]', 'true', '在这个句子中，"学习语文"是主谓短语作主语，"很重要"是谓语。', 2, 3, 2, 'published', '语法知识', 14, 0.82, NOW(), NOW()),
(2, 'essay', '作文片段', '请以"友谊"为话题，写一个100字左右的片段。', '[]', '友谊如春风，温暖人心；友谊如明灯，照亮前路。真正的友谊不在于朝夕相处，而在于心灵相通。当你遇到困难时，朋友会伸出援手；当你取得成功时，朋友会真心祝贺。珍惜身边的每一份友谊，用真诚去维护，用理解去包容，让友谊之花永远绽放。', '这个片段运用了比喻、排比等修辞手法，表达了对友谊的理解和珍视。', 2, 5, 2, 'published', '作文', 8, 0.71, NOW(), NOW()),
(2, 'essay', '古诗文默写', '请默写李白《静夜思》的后两句。', '[]', '举头望明月，低头思故乡。', '这是李白《静夜思》的经典名句，表达了诗人对故乡的思念之情。', 1, 3, 2, 'published', '古诗文默写', 35, 0.92, NOW(), NOW()),
(2, 'single', '字音字形', '"载歌载舞"中"载"的正确读音是？', '["A. zǎi", "B. zài", "C. zhài", "D. cái"]', 'B', '在"载歌载舞"中，"载"读作"zài"，表示"又...又..."的意思。', 1, 2, 2, 'published', '字音字形', 25, 0.88, NOW(), NOW()),
(2, 'single', '文学体裁', '《论语》属于哪种文学体裁？', '["A. 诗歌", "B. 散文", "C. 语录体", "D. 小说"]', 'C', '《论语》是记录孔子及其弟子言行的语录体散文集，属于语录体。', 2, 3, 2, 'published', '文学体裁', 19, 0.84, NOW(), NOW()),
(2, 'single', '修辞识别', '"山重水复疑无路，柳暗花明又一村"主要运用了什么修辞手法？', '["A. 比喻", "B. 拟人", "C. 对偶", "D. 夸张"]', 'C', '这两句诗字数相等，结构相似，意义相关，是典型的对偶句。', 2, 3, 2, 'published', '修辞手法', 17, 0.81, NOW(), NOW()),
(2, 'single', '文言文句式', '"何陋之有"是什么句式？', '["A. 判断句", "B. 被动句", "C. 倒装句", "D. 省略句"]', 'C', '"何陋之有"是宾语前置的倒装句，正常语序应该是"有何陋"。', 3, 4, 2, 'published', '文言文句式', 11, 0.73, NOW(), NOW()),
(2, 'multiple', '现代诗特点', '现代诗具有哪些特点？', '["A. 形式自由", "B. 语言精练", "C. 必须押韵", "D. 意象丰富"]', 'A,B,D', '现代诗的特点包括形式自由、语言精练、意象丰富等，但不一定要押韵。', 2, 4, 2, 'published', '现代诗', 13, 0.76, NOW(), NOW()),
(2, 'judge', '语言规范', '"因为...所以..."句式中，"因为"和"所以"可以同时省略。', '[]', 'false', '在"因为...所以..."句式中，可以省略"因为"或"所以"中的一个，但不能同时省略。', 2, 3, 2, 'published', '语言规范', 21, 0.86, NOW(), NOW()),
(2, 'essay', '文本分析', '分析"采菊东篱下，悠然见南山"体现了怎样的生活态度。', '[]', '体现了诗人淡泊名利、热爱自然、追求精神自由的生活态度，表现了对田园生活的向往和内心的宁静致远。', '这两句诗通过描写采菊和望山的悠闲生活，展现了陶渊明超脱世俗的人生境界。', 3, 5, 2, 'published', '文本分析', 9, 0.68, NOW(), NOW()),
(2, 'essay', '语言运用', '请用"春天、希望、成长"三个词语写一段话。', '[]', '春天来了，万物复苏，到处充满了希望的气息。小草从土里探出头来，树木抽出新芽，孩子们在阳光下快乐地成长。春天不仅是自然界的新生，更是我们心中希望的象征，激励着每个人在新的一年里努力成长，追求更美好的未来。', '这段话围绕三个关键词展开，运用了拟人等修辞手法，表达了积极向上的主题。', 2, 4, 2, 'published', '语言运用', 15, 0.79, NOW(), NOW()),
(2, 'single', '阅读理解', '在议论文中，论据的作用是？', '["A. 提出问题", "B. 证明论点", "C. 总结全文", "D. 引起读者兴趣"]', 'B', '在议论文中，论据是用来证明论点的材料，包括事实论据和道理论据。', 2, 3, 2, 'published', '议论文', 23, 0.87, NOW(), NOW()),

-- 英语题目 (科目ID: 3) - 增加20个题目
(3, 'single', '动词时态', 'By the time you arrive, I _____ for two hours.', '["A. will wait", "B. will have waited", "C. will be waiting", "D. wait"]', 'B', 'By the time引导的时间状语从句，主句用将来完成时will have done。', 3, 4, 2, 'published', '时态', 18, 0.79, NOW(), NOW()),
(3, 'single', '介词用法', 'She is good _____ playing the piano.', '["A. at", "B. in", "C. on", "D. for"]', 'A', 'be good at是固定搭配，表示"擅长于"。', 1, 2, 2, 'published', '介词', 32, 0.94, NOW(), NOW()),
(3, 'single', '词汇辨析', 'The weather is _____ today than yesterday.', '["A. more better", "B. much better", "C. very better", "D. too better"]', 'B', 'better已经是比较级，不能再用more修饰，可以用much修饰比较级表示程度。', 2, 3, 2, 'published', '比较级', 26, 0.85, NOW(), NOW()),
(3, 'single', '从句识别', 'I don''t know _____ he will come tomorrow.', '["A. that", "B. whether", "C. what", "D. which"]', 'B', '这是宾语从句，表示"是否"的意思，用whether引导。', 2, 3, 2, 'published', '从句', 21, 0.81, NOW(), NOW()),
(3, 'single', '被动语态', 'The book _____ by millions of people.', '["A. reads", "B. is read", "C. read", "D. reading"]', 'B', '书被人们阅读，应该用被动语态is read。', 2, 3, 2, 'published', '被动语态', 24, 0.83, NOW(), NOW()),
(3, 'multiple', '情态动词', 'Which modal verbs express possibility?', '["A. can", "B. may", "C. must", "D. might"]', 'A,B,D', 'can, may, might都可以表示可能性，must表示必须或肯定推测。', 2, 4, 2, 'published', '情态动词', 19, 0.76, NOW(), NOW()),
(3, 'multiple', '词性转换', 'Which are correct word formations?', '["A. happy → happiness", "B. quick → quickly", "C. beauty → beautiful", "D. care → careful"]', 'A,B,C,D', '这些都是正确的词性转换：形容词→名词，形容词→副词，名词→形容词，动词→形容词。', 2, 4, 2, 'published', '词性转换', 17, 0.78, NOW(), NOW()),
(3, 'judge', '语法规则', 'Countable nouns can be used with "a" or "an".', '[]', 'true', 'Countable nouns (可数名词) can indeed be used with indefinite articles "a" or "an".', 1, 2, 2, 'published', '名词', 29, 0.91, NOW(), NOW()),
(3, 'judge', '语音知识', 'The letter "c" always makes the /k/ sound.', '[]', 'false', 'The letter "c" can make different sounds, like /k/ in "cat" and /s/ in "city".', 2, 3, 2, 'published', '语音', 22, 0.84, NOW(), NOW()),
(3, 'essay', '写作练习', 'Write a short paragraph about your favorite season.', '[]', 'My favorite season is spring. The weather becomes warmer, flowers bloom everywhere, and trees turn green again. I love to see nature wake up from winter sleep. Spring brings hope and new beginnings. It''s the perfect time for outdoor activities like hiking and picnicking.', 'This paragraph uses simple present tense and descriptive language to express personal preferences.', 2, 5, 2, 'published', '写作', 12, 0.72, NOW(), NOW()),
(3, 'essay', '阅读理解', 'Explain the main idea of this sentence: "Education is the key to success."', '[]', 'This sentence means that getting a good education is very important for achieving success in life. Education provides knowledge, skills, and opportunities that help people reach their goals and improve their lives.', 'The explanation should focus on the metaphor of "key" and the relationship between education and success.', 2, 4, 2, 'published', '阅读理解', 15, 0.75, NOW(), NOW()),
(3, 'single', '固定搭配', 'I''m looking forward _____ hearing from you.', '["A. to", "B. for", "C. at", "D. in"]', 'A', 'look forward to是固定搭配，to是介词，后面跟动名词。', 2, 3, 2, 'published', '固定搭配', 28, 0.86, NOW(), NOW()),
(3, 'single', '疑问句', '_____ do you go to school? By bus.', '["A. What", "B. How", "C. Where", "D. When"]', 'B', '根据回答"By bus"可知问的是方式，用How提问。', 1, 2, 2, 'published', '疑问句', 35, 0.93, NOW(), NOW()),
(3, 'single', '代词用法', 'This book is _____. That one is mine.', '["A. your", "B. yours", "C. you", "D. yourself"]', 'B', '这里需要名词性物主代词yours，相当于your book。', 2, 3, 2, 'published', '代词', 25, 0.88, NOW(), NOW()),
(3, 'single', '连词使用', '_____ it was raining, we decided to stay home.', '["A. Because", "B. Although", "C. If", "D. When"]', 'A', '根据句意"因为下雨，我们决定待在家里"，应该用Because表示原因。', 2, 3, 2, 'published', '连词', 23, 0.82, NOW(), NOW()),
(3, 'single', '形容词比较', 'This is _____ book I have ever read.', '["A. interesting", "B. more interesting", "C. most interesting", "D. the most interesting"]', 'D', '这是最高级的用法，"我读过的最有趣的书"，用the most interesting。', 2, 3, 2, 'published', '最高级', 20, 0.80, NOW(), NOW()),
(3, 'multiple', '句子成分', 'In the sentence "She gave me a book", what are the objects?', '["A. me (indirect object)", "B. a book (direct object)", "C. she (subject)", "D. gave (predicate)"]', 'A,B', 'me是间接宾语，a book是直接宾语。she是主语，gave是谓语。', 3, 4, 2, 'published', '句子成分', 16, 0.74, NOW(), NOW()),
(3, 'judge', '语序规则', 'In English, adjectives usually come after nouns.', '[]', 'false', 'In English, adjectives usually come before nouns, like "a beautiful flower".', 1, 2, 2, 'published', '语序', 31, 0.89, NOW(), NOW()),
(3, 'essay', '语法改错', 'Correct this sentence: "He don''t like apples."', '[]', '"He doesn''t like apples." 或 "He does not like apples."', 'The subject "he" is third person singular, so we need "doesn''t" instead of "don''t".', 1, 3, 2, 'published', '语法改错', 27, 0.87, NOW(), NOW()),
(3, 'essay', '句型转换', 'Change to passive voice: "The teacher teaches English."', '[]', '"English is taught by the teacher."', 'In passive voice, the object becomes the subject, and we use "be + past participle".', 3, 4, 2, 'published', '句型转换', 14, 0.71, NOW(), NOW()),
(3, 'single', '习语理解', 'What does "break a leg" mean?', '["A. hurt yourself", "B. good luck", "C. run fast", "D. be careful"]', 'B', '"Break a leg"是英语习语，意思是"祝你好运"，常用于演出前的祝福。', 3, 4, 2, 'published', '习语', 11, 0.69, NOW(), NOW()),

-- 物理题目 (科目ID: 4) - 增加20个题目
(4, 'single', '运动学', '自由落体运动的加速度大小是？', '["A. 9.8 m/s", "B. 9.8 m/s²", "C. 10 m/s", "D. 10 m/s²"]', 'B', '自由落体运动的加速度是重力加速度g，大小约为9.8 m/s²。', 1, 3, 2, 'published', '自由落体', 28, 0.92, NOW(), NOW()),
(4, 'single', '牛顿定律', '牛顿第二定律的表达式是？', '["A. F = ma", "B. F = mv", "C. F = mg", "D. F = mgh"]', 'A', '牛顿第二定律：物体的加速度与作用力成正比，与质量成反比，即F = ma。', 1, 3, 2, 'published', '牛顿定律', 35, 0.94, NOW(), NOW()),
(4, 'single', '功和能', '重力做功的特点是？', '["A. 只与路径有关", "B. 只与初末位置有关", "C. 与路径和位置都有关", "D. 与时间有关"]', 'B', '重力是保守力，重力做功只与物体初末位置的高度差有关，与路径无关。', 2, 4, 2, 'published', '功和能', 22, 0.86, NOW(), NOW()),
(4, 'single', '电磁学', '库仑定律适用于？', '["A. 运动电荷", "B. 静止点电荷", "C. 电流", "D. 磁场"]', 'B', '库仑定律描述静止点电荷之间的相互作用力，不适用于运动电荷。', 2, 3, 2, 'published', '库仑定律', 19, 0.83, NOW(), NOW()),
(4, 'single', '波动光学', '光的干涉现象说明光具有？', '["A. 粒子性", "B. 波动性", "C. 电磁性", "D. 量子性"]', 'B', '干涉是波的特有现象，光的干涉现象证明了光具有波动性。', 2, 3, 2, 'published', '光的干涉', 16, 0.81, NOW(), NOW()),
(4, 'multiple', '简谐运动', '简谐运动的特征有哪些？', '["A. 周期性", "B. 对称性", "C. 能量守恒", "D. 振幅恒定"]', 'A,B,C,D', '简谐运动具有周期性、对称性，遵循能量守恒，在无阻尼情况下振幅恒定。', 3, 5, 2, 'published', '简谐运动', 14, 0.76, NOW(), NOW()),
(4, 'multiple', '电路分析', '在串联电路中，哪些物理量相等？', '["A. 电流", "B. 电压", "C. 电阻", "D. 功率"]', 'A', '在串联电路中，各处电流相等，电压、电阻、功率一般不相等。', 2, 4, 2, 'published', '串联电路', 25, 0.88, NOW(), NOW()),
(4, 'judge', '热力学', '热量可以自发地从低温物体传递到高温物体。', '[]', 'false', '根据热力学第二定律，热量不能自发地从低温物体传递到高温物体。', 2, 3, 2, 'published', '热力学定律', 18, 0.85, NOW(), NOW()),
(4, 'judge', '相对论', '在真空中，光速对所有惯性参考系都相同。', '[]', 'true', '这是爱因斯坦相对论的基本假设之一：光速不变原理。', 3, 4, 2, 'published', '相对论', 12, 0.73, NOW(), NOW()),
(4, 'essay', '力学计算', '质量为2kg的物体在水平面上受到10N的水平拉力，摩擦系数为0.2，求物体的加速度。', '[]', 'a = 3 m/s²', '摩擦力f = μmg = 0.2×2×10 = 4N，合力F合 = 10-4 = 6N，加速度a = F合/m = 6/2 = 3 m/s²。', 2, 5, 2, 'published', '力学计算', 20, 0.78, NOW(), NOW()),
(4, 'essay', '电学计算', '电阻为6Ω的导体两端电压为12V，求通过的电流和消耗的功率。', '[]', 'I = 2A, P = 24W', '根据欧姆定律：I = U/R = 12/6 = 2A，功率P = UI = 12×2 = 24W。', 2, 4, 2, 'published', '电学计算', 23, 0.82, NOW(), NOW()),
(4, 'single', '原子物理', '氢原子的基态能级是？', '["A. -13.6 eV", "B. -3.4 eV", "C. -1.5 eV", "D. 0 eV"]', 'A', '氢原子的基态（n=1）能级为-13.6 eV，这是氢原子能级的最低值。', 3, 4, 2, 'published', '原子物理', 15, 0.74, NOW(), NOW()),
(4, 'single', '磁场', '通电直导线周围的磁场方向由什么确定？', '["A. 左手定则", "B. 右手定则", "C. 楞次定律", "D. 法拉第定律"]', 'B', '通电直导线周围磁场方向由右手定则确定：右手握拳，拇指指向电流方向，四指弯曲方向为磁场方向。', 2, 3, 2, 'published', '磁场', 26, 0.87, NOW(), NOW()),
(4, 'single', '机械振动', '单摆的周期公式是？', '["A. T = 2π√(l/g)", "B. T = 2π√(g/l)", "C. T = π√(l/g)", "D. T = π√(g/l)"]', 'A', '单摆的周期公式为T = 2π√(l/g)，其中l是摆长，g是重力加速度。', 2, 4, 2, 'published', '单摆', 17, 0.79, NOW(), NOW()),
(4, 'single', '流体力学', '阿基米德原理说明了什么？', '["A. 浮力大小", "B. 压强分布", "C. 流速关系", "D. 密度变化"]', 'A', '阿基米德原理：浸在流体中的物体受到的浮力等于它排开流体的重量。', 2, 3, 2, 'published', '浮力', 21, 0.84, NOW(), NOW()),
(4, 'single', '量子力学', '光电效应中，光电子的最大初动能取决于？', '["A. 光的强度", "B. 光的频率", "C. 照射时间", "D. 金属种类和光频率"]', 'D', '根据爱因斯坦光电效应方程：Ek = hν - W₀，最大初动能取决于光频率和金属的逸出功。', 3, 4, 2, 'published', '光电效应', 13, 0.71, NOW(), NOW()),
(4, 'multiple', '能量转换', '下列哪些过程涉及能量转换？', '["A. 发电机发电", "B. 电动机转动", "C. 太阳能电池", "D. 摩擦生热"]', 'A,B,C,D', '这些都涉及能量转换：机械能→电能，电能→机械能，光能→电能，机械能→内能。', 2, 4, 2, 'published', '能量转换', 19, 0.80, NOW(), NOW()),
(4, 'judge', '电磁感应', '导体在磁场中运动一定会产生感应电流。', '[]', 'false', '导体在磁场中运动，只有当磁通量发生变化时才会产生感应电动势，形成闭合回路才有感应电流。', 2, 3, 2, 'published', '电磁感应', 24, 0.83, NOW(), NOW()),
(4, 'essay', '光学计算', '凸透镜焦距为20cm，物体距透镜30cm，求像距和放大倍数。', '[]', '像距v = 60cm，放大倍数m = -2', '根据透镜公式1/f = 1/u + 1/v：1/20 = 1/30 + 1/v，解得v = 60cm；放大倍数m = -v/u = -60/30 = -2。', 3, 5, 2, 'published', '透镜成像', 16, 0.75, NOW(), NOW()),
(4, 'essay', '动量守恒', '质量为2kg的小球以5m/s的速度与质量为3kg的静止小球发生弹性碰撞，求碰撞后两球的速度。', '[]', 'v₁ = -1 m/s, v₂ = 4 m/s', '根据动量守恒和能量守恒：2×5 = 2v₁ + 3v₂，½×2×25 = ½×2v₁² + ½×3v₂²，解得v₁ = -1 m/s，v₂ = 4 m/s。', 3, 6, 2, 'published', '碰撞', 11, 0.68, NOW(), NOW()),
(4, 'single', '热学', '理想气体状态方程是？', '["A. PV = nRT", "B. PV = RT", "C. P = nRT", "D. V = nRT"]', 'A', '理想气体状态方程为PV = nRT，其中P是压强，V是体积，n是摩尔数，R是气体常数，T是温度。', 2, 3, 2, 'published', '理想气体', 27, 0.89, NOW(), NOW()),

-- 化学题目 (科目ID: 5) - 增加20个题目
(5, 'single', '原子结构', '氯原子的电子排布式是？', '["A. 1s²2s²2p⁶3s²3p⁵", "B. 1s²2s²2p⁶3s²3p⁶", "C. 1s²2s²2p⁶3s¹3p⁶", "D. 1s²2s²2p⁵3s²3p⁶"]', 'A', '氯原子有17个电子，电子排布为1s²2s²2p⁶3s²3p⁵。', 2, 3, 2, 'published', '电子排布', 22, 0.86, NOW(), NOW()),
(5, 'single', '化学键', '下列化合物中含有离子键的是？', '["A. H₂O", "B. CO₂", "C. NaCl", "D. CH₄"]', 'C', 'NaCl是由金属钠和非金属氯形成的离子化合物，含有离子键。', 1, 3, 2, 'published', '化学键', 28, 0.91, NOW(), NOW()),
(5, 'single', '化学反应', '下列反应属于氧化还原反应的是？', '["A. NaOH + HCl → NaCl + H₂O", "B. CaCO₃ → CaO + CO₂", "C. 2H₂ + O₂ → 2H₂O", "D. AgNO₃ + NaCl → AgCl + NaNO₃"]', 'C', '氢气燃烧反应中，氢元素化合价从0变为+1，氧元素化合价从0变为-2，有电子转移。', 2, 4, 2, 'published', '氧化还原', 25, 0.84, NOW(), NOW()),
(5, 'single', '酸碱盐', 'pH = 7的溶液是？', '["A. 酸性", "B. 碱性", "C. 中性", "D. 无法确定"]', 'C', 'pH = 7表示溶液中氢离子浓度等于氢氧根离子浓度，溶液呈中性。', 1, 2, 2, 'published', 'pH值', 35, 0.95, NOW(), NOW()),
(5, 'single', '有机化学', '甲烷的分子式是？', '["A. CH₂", "B. CH₃", "C. CH₄", "D. C₂H₆"]', 'C', '甲烷是最简单的烷烃，分子式为CH₄，含有一个碳原子和四个氢原子。', 1, 2, 2, 'published', '烷烃', 32, 0.94, NOW(), NOW()),
(5, 'multiple', '元素周期律', '同一周期元素从左到右的变化规律有？', '["A. 原子半径递减", "B. 金属性递减", "C. 非金属性递增", "D. 原子序数递增"]', 'A,B,C,D', '同周期从左到右：原子序数递增，原子半径递减，金属性递减，非金属性递增。', 2, 4, 2, 'published', '周期律', 19, 0.81, NOW(), NOW()),
(5, 'multiple', '化学实验', '使用酒精灯时应注意哪些安全事项？', '["A. 不能用嘴吹灭", "B. 酒精不能超过灯壶的2/3", "C. 用灯帽盖灭", "D. 可以向燃着的酒精灯添加酒精"]', 'A,B,C', '酒精灯使用安全：不能用嘴吹灭，酒精量不超过2/3，用灯帽盖灭，不能向燃着的灯添加酒精。', 1, 3, 2, 'published', '实验安全', 30, 0.88, NOW(), NOW()),
(5, 'judge', '化学平衡', '增大压强，化学平衡一定向气体分子数减少的方向移动。', '[]', 'false', '只有当反应前后气体分子数不等时，增大压强才会使平衡移动；若气体分子数相等，压强不影响平衡。', 3, 4, 2, 'published', '化学平衡', 16, 0.75, NOW(), NOW()),
(5, 'judge', '溶液', '饱和溶液一定是浓溶液。', '[]', 'false', '饱和溶液是指在一定温度下不能再溶解该溶质的溶液，但不一定是浓溶液，如石灰水。', 2, 3, 2, 'published', '溶液', 24, 0.83, NOW(), NOW()),
(5, 'essay', '化学计算', '计算32g氧气在标准状况下的体积。', '[]', 'V = 22.4 L', '氧气的摩尔质量为32 g/mol，32g氧气的物质的量为1 mol，标准状况下体积为22.4 L。', 2, 4, 2, 'published', '气体计算', 21, 0.79, NOW(), NOW()),
(5, 'essay', '方程式书写', '写出铁与稀硫酸反应的化学方程式。', '[]', 'Fe + H₂SO₄ → FeSO₄ + H₂↑', '铁与稀硫酸反应生成硫酸亚铁和氢气，注意氢气要标上升号。', 1, 3, 2, 'published', '化学方程式', 27, 0.87, NOW(), NOW()),
(5, 'single', '金属活动性', '下列金属中活动性最强的是？', '["A. 铁", "B. 铜", "C. 锌", "D. 镁"]', 'D', '根据金属活动性顺序：K Ca Na Mg Al Zn Fe...，镁的活动性最强。', 2, 3, 2, 'published', '金属活动性', 26, 0.85, NOW(), NOW()),
(5, 'single', '化学式', '硫酸的化学式是？', '["A. H₂S", "B. H₂SO₃", "C. H₂SO₄", "D. SO₃"]', 'C', '硫酸是强酸，化学式为H₂SO₄，含有两个氢原子、一个硫原子和四个氧原子。', 1, 2, 2, 'published', '化学式', 33, 0.93, NOW(), NOW()),
(5, 'single', '化学反应类型', '反应CuO + H₂ → Cu + H₂O属于？', '["A. 化合反应", "B. 分解反应", "C. 置换反应", "D. 复分解反应"]', 'C', '氢气置换出氧化铜中的铜，属于置换反应（单质+化合物→单质+化合物）。', 2, 3, 2, 'published', '反应类型', 23, 0.82, NOW(), NOW()),
(5, 'single', '物质分类', '下列物质属于纯净物的是？', '["A. 空气", "B. 海水", "C. 蒸馏水", "D. 钢铁"]', 'C', '蒸馏水是纯净的H₂O，属于纯净物；其他都是混合物。', 1, 2, 2, 'published', '物质分类', 31, 0.92, NOW(), NOW()),
(5, 'single', '化学性质', '下列属于化学性质的是？', '["A. 颜色", "B. 状态", "C. 可燃性", "D. 密度"]', 'C', '可燃性需要通过化学反应才能表现出来，属于化学性质；其他都是物理性质。', 1, 3, 2, 'published', '化学性质', 29, 0.90, NOW(), NOW()),
(5, 'multiple', '化学用语', '下列化学用语正确的是？', '["A. 氯离子：Cl⁻", "B. 2个氢原子：2H", "C. 氧化镁：MgO", "D. 硫酸根离子：SO₄²⁻"]', 'A,B,C,D', '这些化学用语都是正确的：离子符号、原子个数表示、化学式、离子符号。', 1, 3, 2, 'published', '化学用语', 28, 0.89, NOW(), NOW()),
(5, 'judge', '化学反应条件', '所有的化学反应都需要加热才能进行。', '[]', 'false', '许多化学反应在常温下就能进行，如酸碱中和反应、金属与酸的反应等。', 1, 2, 2, 'published', '反应条件', 34, 0.91, NOW(), NOW()),
(5, 'essay', '实验设计', '设计实验证明二氧化碳的性质：密度比空气大。', '[]', '将燃着的蜡烛放在烧杯底部，向烧杯中倾倒二氧化碳气体，观察到蜡烛熄灭，说明二氧化碳密度比空气大，沉在底部。', '利用二氧化碳不支持燃烧和密度大的性质设计实验，通过现象说明问题。', 2, 5, 2, 'published', '实验设计', 18, 0.76, NOW(), NOW()),
(5, 'essay', '化学与生活', '说明小苏打在生活中的应用及原理。', '[]', '小苏打可用于发面（受热分解产生CO₂）、治疗胃酸过多（中和胃酸）、清洁剂（弱碱性）等。', '碳酸氢钠的化学性质决定了它在生活中的多种用途。', 2, 4, 2, 'published', '化学与生活', 20, 0.78, NOW(), NOW());